CREATE DATABASE IF NOT EXISTS HospitalDB;
USE HospitalDB;

CREATE TABLE Department (
  DepartmentID INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(100) NOT NULL UNIQUE,
  Phone VARCHAR(20) NOT NULL
);

CREATE TABLE Staff (
  StaffID INT AUTO_INCREMENT PRIMARY KEY,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  JobTitle VARCHAR(50) NOT NULL,
  HireDate DATE NOT NULL,
  DaysOffTaken INT DEFAULT 0,
  DepartmentID INT NOT NULL,
  FOREIGN KEY (DepartmentID) REFERENCES Department(DepartmentID)
);

CREATE TABLE Patient (
  PatientID INT AUTO_INCREMENT PRIMARY KEY,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  Address VARCHAR(120) NOT NULL,
  Phone VARCHAR(20) NOT NULL,
  MedicalHistory TEXT,
  DepartmentID INT NOT NULL,
  FOREIGN KEY (DepartmentID) REFERENCES Department(DepartmentID)
);

CREATE TABLE Treatment (
  TreatmentID INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(100) NOT NULL UNIQUE,
  Description VARCHAR(255)
);

CREATE TABLE Appointment (
  AppointmentID INT AUTO_INCREMENT PRIMARY KEY,
  AppointmentDate DATE NOT NULL,
  AppointmentTime TIME NOT NULL,
  PatientID INT NOT NULL,
  StaffID INT NOT NULL,
  TreatmentID INT NOT NULL,
  FOREIGN KEY (PatientID) REFERENCES Patient(PatientID) ON DELETE CASCADE,
  FOREIGN KEY (StaffID) REFERENCES Staff(StaffID) ON DELETE CASCADE,
  FOREIGN KEY (TreatmentID) REFERENCES Treatment(TreatmentID) ON DELETE RESTRICT
);
